// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlb_z8422MrKD1SpDaKyySAfl2tHTdqfo',
    appId: '1:806191194387:web:5ce72d304fd7e65943fae6',
    messagingSenderId: '806191194387',
    projectId: 'mickaelpottodoflutter',
    authDomain: 'mickaelpottodoflutter.firebaseapp.com',
    storageBucket: 'mickaelpottodoflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3nVNx061JQ4uNR75l4xugMkVnY0N2ew',
    appId: '1:806191194387:android:395e15d87f6f4a7d43fae6',
    messagingSenderId: '806191194387',
    projectId: 'mickaelpottodoflutter',
    storageBucket: 'mickaelpottodoflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02mhgc2asuf7wcPHVMmfCFpRNIxFcqkw',
    appId: '1:806191194387:ios:fe37546551f69d8643fae6',
    messagingSenderId: '806191194387',
    projectId: 'mickaelpottodoflutter',
    storageBucket: 'mickaelpottodoflutter.appspot.com',
    iosClientId: '806191194387-t6n14c1j9f4fvpripku2sqldaphq154f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mickaelToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02mhgc2asuf7wcPHVMmfCFpRNIxFcqkw',
    appId: '1:806191194387:ios:8d88600c17ef67dc43fae6',
    messagingSenderId: '806191194387',
    projectId: 'mickaelpottodoflutter',
    storageBucket: 'mickaelpottodoflutter.appspot.com',
    iosClientId: '806191194387-u09cif19aobiu6jlankuj97pn5m4uoa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mickaelToDo.RunnerTests',
  );
}
